project/mainApp/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('registration/', views.register, name = 'registration'),
    path('', views.login, name = 'login'),
    path('main/', views.mainPage, name = 'main'),
    path('logout/', views.logoutUser, name='logout'),
    path('groups/', views.list_group, name='groups'),
    path('groups/group=<detail_group>/', views.detail_group, name ='detail_group'),
    path('groups/group=<detail_group>/create_dis',views.create_dis, name = "create_dis"),
    path('groups/group=<detail_group>/course=<list_courses>/',views.list_courses, name ='list_courses'),
    path('courses/',views.student_courses, name = 'student_courses'),
    path('courses/course=<stud_course>/',views.stud_course, name='stud_course'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
]

project/mainApp/models.py
from django.db import models
from django.apps import apps
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group
from django.utils import timezone
from django.conf import settings
# Create your models here.

class User(AbstractUser):
    middlename = models.CharField(max_length=50)
    group = (
        ('02121-ДБ','02121-ДБ'),('02122-ДБ','02122-ДБ'),('02141-ДБ','02141-ДБ'),('02161-ДБ','02161-ДБ'),
        ('02171-ДБ','02171-ДБ'),('02172-ДБ','02172-ДБ'),('02173-ДБ','02173-ДБ'),
        ('02221-ДБ','02221-ДБ'),('02222-ДБ','02222-ДБ'),('02241-ДБ','02241-ДБ'),
        ('02242-ДБ','02242-ДБ'),('02261-ДБ','02261-ДБ'),('02271-ДБ','02271-ДБ'),
        ('02311-ДБ','02311-ДБ'),('02321-ДБ','02321-ДБ'),('02322-ДБ','02322-ДБ'),
        ('02341-ДБ','02341-ДБ'),('02361-ДБ','02361-ДБ'),('02371-ДБ','02371-ДБ'),
        ('02411-ДБ','02411-ДБ'),('02421-ДБ','02421-ДБ'),('02422-ДБ','02422-ДБ'),
        ('02441-ДБ','02441-ДБ'),('02461-ДБ','02461-ДБ'),('02471-ДБ','02471-ДБ')
    )
    group = models.CharField(max_length=30,choices=group,default='02121-ДБ',blank=True, null=True)
    role = (
        ('Студент','Студент'), ('Преподаватель','Преподаватель')
    )
    role = models.CharField(max_length=50,choices=role, default='Студент')

class Discipline(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    course = models.CharField(max_length=50)
    def __str__(self):
        return '%s %s' % (self.course, self.User.username)

class Attendance(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Discipline,on_delete=models.CASCADE)
    status = (
    ('+','+'),('-','-')
    )
    status = models.CharField(max_length=1,choices=status, default='-',blank=True, null=True)
    data = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return '%s %s %s' % (self.User.username, str(self.data), self.course)

project/mainApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from . models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2','first_name','last_name','middlename','group','role')

class create_dis_form(forms.ModelForm):
    class Meta:
        model = Discipline
        fields = ['course']
        widgets = {
            'course':forms.TextInput(attrs={'class': 'form-control'}),
        }

class table_col(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = ['data']
        widgets ={
            'data' : forms.DateTimeInput(attrs={'class': 'form-control datetimepicker-input','data-target': '#datetimepicker1'})
        }

project/mainApp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as djanjologin
from . forms import *
from . models import *
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import dateformat
from django.conf import settings
from django.urls import reverse

# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect('main')
    else:
        formreg = CreateUserForm(request.POST or None)
        if request.method == 'POST' and formreg.is_valid():
            new_user = formreg.save(commit=False)
            new_user.username = formreg.cleaned_data['username']
            new_user.password1 = formreg.cleaned_data['password1']    
            new_user.middlename = formreg.cleaned_data['middlename']
            new_user.group = formreg.cleaned_data['group']
            new_user.role = formreg.cleaned_data['role']
            new_user.save()
            if formreg.cleaned_data['role'] == 'Преподаватель':
                new_user.groups.add(Group.objects.get(name='Преподаватели'))
            else:
                new_user.groups.add(Group.objects.get(name='Студенты'))
                new_user.groups.add(Group.objects.get(name = formreg.cleaned_data['group']))
            return redirect('login')
        return render(request, 'mainApp/register.html',{'formreg':formreg})

def login(request):
    if request.user.is_authenticated:
        return redirect('main')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password = password)
            if user is not None:
                djanjologin(request, user)
                return redirect('main')
            else:
                messages.info(request, 'Логин или пароль введен неверно')
        return render(request, 'mainApp/login.html')
    
def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
def mainPage(request):
    return render(request,"mainApp/mainPage.html")

@login_required(login_url='login')
def list_group(request):
    if request.user.role == 'Преподаватель':
        groups_list = Group.objects.all()
        return render(request,"mainApp/group.html",{'groups_list':groups_list})
    else: 
        return redirect('main')

@login_required(login_url='login')
def detail_group(request,detail_group):
    if request.user.role == 'Преподаватель':
        group = Group.objects.get(id = detail_group)
        courses = Discipline.objects.all()
        return render(request,"mainApp/list_courses.html",{'group':group,'courses':courses})
        #return render(request, "mainApp/detail_group.html", {'group':group,'users':users,'attendance':attendance,'courses':courses})
    else: 
        return redirect('main')

@login_required(login_url='login')
def list_courses(request,detail_group,list_courses):
    if request.user.role == 'Преподаватель':
        group = Group.objects.get(id = detail_group)
        users = group.user_set.all()
        attendance = Attendance.objects.order_by('data')
        data_select = Attendance.objects.filter(User = users[0]).order_by('data')
        course = Discipline.objects.get(id = list_courses)
        if request.POST:
            if request.POST.get("form_type") == 'Добавить':
                date_cal = request.POST.get('form_type_1')
                for i in users:
                    a = Attendance(User = i,course = course, status = '-', data = date_cal)
                    a.save()      
                return redirect('list_courses', detail_group=group.id,list_courses=course.id)
                    
            elif request.POST.get("form_type_2") == 'Удалить':
                date_sel = request.POST.get('form_type2')
                att = Attendance.objects.all()
                for i in att:
                    if dateformat.format(i.data, settings.DATE_FORMAT) == date_sel:
                        d = Attendance.objects.get(id = i.id) 
                        d.delete() 
                return redirect('list_courses', detail_group=group.id,list_courses=course.id)
            else:
                for j in attendance:
                    if j.course.course == course.course and j.User.group == group.name:
                        st = request.POST.get('in_checkbox='+str(j.id))
                        ob_st = Attendance.objects.get(id = j.id)
                        if st == 'on':
                            ob_st.status = '+'
                        else:
                            ob_st.status = '-'
                        ob_st.save()
                return redirect('list_courses', detail_group=group.id,list_courses=course.id)
        return render(request,"mainApp/table.html",{'data_select':data_select,'users':users,'attendance':attendance,'group':group,'course':course})
    else: 
        return redirect('main')

@login_required(login_url='login')
def create_dis(request,detail_group):
    if request.user.role == 'Преподаватель':
        group = Group.objects.get(id = detail_group)
        courses = Discipline.objects.all()
        form = create_dis_form(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            users = group.user_set.all()
            new_dis = form.save(commit=False)
            new_dis.User = request.user
            new_dis.group = group
            new_dis.course = form.cleaned_data['course']
            for i in users:
                if i.role == 'Студент':
                    a = Discipline(User = i, group = group, course = form.cleaned_data['course'])
                    a.save()
            new_dis.save()
            return render(request,"mainApp/list_courses.html",{'group':group,'courses':courses})
        return render(request, 'mainApp/create_dis.html',{'form':form,'group':group})
    else: 
        return redirect('main')

@login_required(login_url='login')
def student_courses(request):
    if request.user.role == 'Студент':
        dis = Discipline.objects.all()
        return render(request,'mainApp/student_courses.html',{'dis':dis})
    else: 
        return redirect('main')

@login_required(login_url='login')
def stud_course(request,stud_course):
    if request.user.role == 'Студент':
        dis = Discipline.objects.get(id = stud_course)
        courses = Discipline.objects.all() 
        group = Group.objects.get(name = request.user.group)
        users = group.user_set.all()
        attendance = Attendance.objects.order_by('data')
        return render(request,'mainApp/stud_course.html',{'courses':courses,'users':users,'attendance':attendance,'dis':dis})
    else: 
        return redirect('main')

project/mainApp/templates/mainApp/create_dis.html
{% extends 'mainApp/mainPage.html' %}

{% block content%}
    <form class="col-3 mt-3" action="{% url 'create_dis' detail_group=group.id %}" method="POST">
        {% csrf_token %}

        {% for i in form %}
            <div class="form-group">
                {% if i.errors %}
                    <div class="alert alert-danger">
                        {{i.errors}}
                    </div>
                {% endif %}
                <label>Название дисциплины</label>
                {{ i }}
            </div>
        {% endfor %}
        <button class="btn waves-effect waves-light btn-grd-inverse" type="submit" name="button_dis"> Добавить дисциплину </button>
    </form>
{% endblock %}

project/mainApp/templates/mainApp/group.html
{% extends 'mainApp/mainPage.html' %}

{% block content%}
    <div class="row">
        <div class=" col-4 mt-3"></div>
        <div class=" col-4 mt-3">
            <div class="header-h1 mt-2">
                <h1>Список групп</h1>
            </div>
        </div>                 
        <div class=" col-4 mt-3"></div>
    </div>
    <table class="table table-hover table-condensed mt-3">
      <thead>
          <tr style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 51%, #4c626d 100%);color: #fff;">
              <td>Группы</td>
              <td style="display: flex; justify-content: flex-end;"><b>Ссылка</b></td>
          </tr>
      </thead>
      <tbody>
            {% for i in groups_list %}
            <tr>     
                {% if i.name == "Преподаватели" %}
                
                {% else %}
                    {% if i.name == "Студенты" %}
                    
                    {% else %}
                        <td>{{i.name}}</td>
                        <td><a href="{% url 'detail_group' detail_group=i.id %}" style="display: flex; justify-content: flex-end;">Перейти к группе</a></td>
                    {% endif %}
                {% endif %}
            </tr>
            {% endfor %}
      </tbody>
    </table>
{% endblock %}

project/mainApp/templates/mainApp/list_courses.html
{% extends 'mainApp/mainPage.html' %}

{% block content%}
    <div class="row">
        <div class=" col-4 mt-3"></div>
        <div class=" col-4 mt-3">
            <div class="header-h1 mt-3">
                <h1>Список дисциплин группы:{{group.name}} </h1>
            </div>
        </div>                 
        <div class=" col-4 mt-3"></div>
    </div>
    <div class="btn-group mt-2">
        <a href="create_dis" class="btn waves-effect waves-light btn-grd-inverse" role="button" aria-pressed="true">Добавить дисциплину</a>
    </div>
    <table class="table table-hover table-condensed mt-3">
      <thead>
          <tr style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 51%, #4c626d 100%);color: #fff;">
              <td>Дисциплина</td>
              <td style="display: flex; justify-content: flex-end;"><b>Ссылка</b></td>
          </tr>
      </thead>
      <tbody>
            {% for i in courses %}
                {% if i.group == group%}
                    {% if i.User == request.user %}
                        <tr>      
                            <td>{{i.course}}</td>
                            <td><a href="{% url 'list_courses' detail_group=group.id list_courses=i.id %}" style="display: flex; justify-content: flex-end;">Перейти к группе</a></td>
                        </tr>
                    {% else %}
                    {% endif %}
                {% else%}
                {% endif%}
            {% endfor %}
      </tbody>
    </table>
{% endblock %}

project/mainApp/templates/mainApp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Авторизация</title>
    <style type="text/css">
        .form-group {
            clear:both; 
            text-align:right;
        }
        label {
            float:left;
        }
        .rega{
            width: 300px;
            margin: auto;

        }
        .outer{
            display: flex;
            width: 100%;
            height: 100%;
        }
        html, body{
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background: #DCDCDC;
        }


    </style>
</head>
<body >
    <div class="outer">
        <div class="rega" >
            <form method="POST" style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;">
                {% csrf_token %}
                <div class="form-control" style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;"> 
                    <h3>Авторизация</h3>
                        <div class="form-group" style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;">                
                            <div class="form-control" style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;"> 
                                <label>Логин</label>
                                <input name="username">
                            </div>                       
                        </div>
                        <div class="form-group" style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;">                
                            <div class="form-control" style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;"> 
                                <label>Пароль</label>
                                <input name="password" type="password">
                            </div>                       
                        </div>
                </div>  
                <div class="mt-4">
                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn waves-effect waves-light btn-grd-inverse" type="submit" value="Войти">
                    </div>
                    <div class="d-flex justify-content-center links">
						<p class="test">Нет аккаунта?</p>
						<br>
						<a href="{% url 'registration' %}" class="ml-2">Регистрация</a>
					</div>
				</div>    
            </form>  
        </div>
    </div>
</body>
</html>

project/mainApp/templates/mainApp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Посещаемость</title>
</head>
<body>
    Мы зарегались
</body>
</html>

project/mainApp/templates/mainApp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>
    <style type="text/css">
        .form-group {
            clear:both; 
            text-align:right;
        }
        label {
            float:left;
        }
        .rega{
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .rega{
            width: 500px;
            margin: auto;

        }
        .outer{
            display: flex;
            width: 100%;
            height: 100%;
        }
        html, body{
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background: #DCDCDC;
        }

    </style>
</head>
<body class="">
    <div class="outer">
        <div class="rega" >
            <form method="POST" style="background: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;">
                {% csrf_token %}
                <div class="form-control" style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;"> 
                    <h3>Регистрация</h3>
                    {% for field in formreg %}
                        <div class="form-group" style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;">  
                            {{ field.errors }}               
                            <div class="form-control" style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 41%, #4c626d 100%);color: #fff;"> 
                                {% if field == formreg.role %}
                                <label>Зарегистрироваться как:</label>
                                <select name="role" id="id_role" onChange="Selected(this)">
                                    <option value="Студент" selected="">Студент</option>   
                                    <option value="Преподаватель">Преподаватель</option>                              
                                  </select>
                                {% else %}
                                    {% if field == formreg.middlename %}
                                        <label>Отчество:</label>
                                        {{ field }}                                 
                                    {% else %}
                                        {% if field == formreg.group %}
                                            <label>Группа:</label>
                                            {{field}}
                                        {% else %}
                                            {{ field.label_tag }}{{ field }}
                                        {% endif %}
                                    {% endif%}
                                {% endif %}
                            </div>                       
                        </div>
                    {% endfor %}   
                </div>  
                <div class="mt-4">
                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn waves-effect waves-light btn-grd-inverse" type="submit" value="Зарегистрироваться">
                      </div>
					<div class="d-flex justify-content-center links">
						<p>Уже есть аккаунт?</p> <a href="{% url 'login' %}" class="ml-2">Войти</a>
					</div>
				</div>    
            </form>  
        </div>
    </div>
    <script>
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].required= true;
        form_fields[2].required= true;
        form_fields[3].required= true;
        form_fields[4].required= true;
        form_fields[5].required= true;
        form_fields[6].required= true;
        form_fields[7].required= true;
        function Selected(a) {
            var label = a.value;
            if (label == 'Студент') {
                var form_fields2 = document.getElementsByTagName('input')
                form_fields2[1].required= true;
                form_fields2[2].required= true;
                form_fields2[3].required= true;
                form_fields2[4].required= true;
                form_fields2[5].required= true;
                form_fields2[6].required= true;
                form_fields2[7].required= true;
                var fields1 = document.getElementsByClassName('form-group')
                fields1[6].style.display = 'block'
                var fields2 = document.getElementsByClassName('form-group')
                fields2[6].style.display = 'block'
            }
            else if (label=='Преподаватель') {
                var form_fields3 = document.getElementsByTagName('input')
                form_fields3[1].required= true;
                form_fields3[2].required= true;
                form_fields3[3].required= true;
                form_fields3[4].required= true;
                form_fields3[5].required= true;
                form_fields3[6].required= true;
                form_fields3[7].required= false;
                var fields3 = document.getElementsByClassName('form-group')
                fields3[6].style.display = 'None'
                var fields4 = document.getElementsByClassName('form-group')
                fields4[6].style.display = 'None'
            }
        }
    </script>
</body>
</html>

project/mainApp/templates/mainApp/stud_course.html
{% extends 'mainApp/mainPage.html' %}

{% block content%}
<div class="row">
    <div class=" col-4 mt-3"></div>
    <div class=" col-4 mt-3">
        <div class="header-h1 mt-2">
            <h1>Дисциплина<br> {{dis.course}}<br>
                Группа {{request.user.group}}<br>
                {% for i in courses %}
                    {% if i.course == dis.course %}
                        {% if i.User.role == "Преподаватель" %}
                            Преподаватель <br>{{i.User.last_name}} {{i.User.first_name}} {{i.User.middlename}}
                        {% endif %}
                    {% endif %}
                {% endfor%}
            </h1>
        </div>

    </div>                 
    <div class=" col-4 mt-3"></div>
</div>
<div class="all_groups mt-2">  
    <div class="div_row">
        <div class="div_name">
            <h6>Студенты</h6>
        </div>
        {% for i in attendance %}
            {% if i.course.course == dis.course %}
                {% if users.0 == i.User %}
                    <div class="div_status">
                        {{i.data|date:"d-n-Y"}}
                    </div>
                {% endif %}    
            {% endif %}
        {% endfor %}
    </div>
    {% for i in users %}
        <div class ="div_row">
            <div class="div_name">
                <h6>{{i.last_name}} {{i.first_name}} {{i.middlename}}</h6>
            </div>
            {%  for j in attendance %}
                {% if i == j.User %}
                    {% if j.course.course == dis.course %}
                        <div class="div_status">
                            {% if j.status == '+' %}
                                <input class="in_check" name = "in_checkbox={{j.id}}" type="checkbox"  onclick="p(event)" checked>
                            {% else %}
                                <input class="in_check" name = "in_checkbox={{j.id}}" type="checkbox"  onclick="p(event)">
                            {% endif %}
                        </div>
                    {% endif %}
                {% endif%}
            {%  endfor %}
        </div>
    {% endfor %}
</div>

<script>
    var check_test = true
    function p(e) {
        if (check_test){
            e.preventDefault();
            return false;
        }    
    };
</script>


{% endblock %}

project/mainApp/templates/mainApp/student_courses.html
{% extends 'mainApp/mainPage.html' %}

{% block content %}
<div class="row">
    <div class=" col-4 mt-3"></div>
    <div class=" col-4 mt-3">
        <div class="header-h1 mt-3">
            <h1>Студент:{{request.user.last_name}} {{request.user.first_name}} {{request.user.middlename}} </h1>
        </div>
    </div>                 
    <div class=" col-4 mt-3"></div>
</div>
<table class="table table-hover table-condensed mt-3">
    <thead>
        <tr style="background-image: linear-gradient(to right, #4c626d 0%, #1e272b 51%, #4c626d 100%);color: #fff;">
            <td>Список посещаемых дисциплин</td>
            <td>Преподаватель</td>
            <td style="display: flex; justify-content: flex-end;"><b>Ссылка</b></td>
        </tr>
    </thead>
    <tbody>
        {% for i in dis %}
            {% if request.user == i.User %}
                <tr>
                    <td>{{i.course}}</td>
                    {% for j in dis %}
                        {% if i.course == j.course %}
                            {% if j.User.role == "Преподаватель" %}
                                <td>{{j.User.last_name}} {{j.User.first_name}} {{j.User.middlename}}</td>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    <td><a href="{% url 'stud_course' stud_course=i.id %}" style="display: flex; justify-content: flex-end;">Перейти к дисциплине</a></td>
                </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}